quarkus.http.port=8080

# DataSource ? PostgreSQL (ver local/docker-compose.yml)
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=gerente
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/banco_db

# Hibernate ORM
quarkus.hibernate-orm.database.generation=none
quarkus.hibernate-orm.log.sql=true

# ---------------------------------------------------------------
# JWT ? Segurança
# ---------------------------------------------------------------
mp.jwt.verify.publickey.location=publicKey.pem
mp.jwt.verify.issuer=trabalho-final-api
smallrye.jwt.sign.key.location=privateKey.pem

# Trata os requests fazendo com que a aplicação aceite somente o esperado no DTO
quarkus.jackson.fail-on-unknown-properties=true
