quarkus.http.port=8080

# DataSource ? PostgreSQL (ver local/docker-compose.yml)
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=gerente
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/banco_db

# Hibernate ORM
quarkus.hibernate-orm.database.generation=none
quarkus.hibernate-orm.log.sql=true

# ---------------------------------------------------------------
# JWT ? Segurança
# ---------------------------------------------------------------
mp.jwt.verify.publickey.location=publicKey.pem
mp.jwt.verify.issuer=trabalho-final-api
smallrye.jwt.sign.key.location=privateKey.pem

# Trata os requests fazendo com que a aplicação aceite somente o esperado no DTO
quarkus.jackson.fail-on-unknown-properties=true

# testes
# configura uma porta aleatória para testes
quarkus.http.test-port=0

#jacoco
quarkus.jacoco.data-file=target/jacoco.exec
quarkus.jacoco.report-location=target/jacoco-report
quarkus.jacoco.excludes=\
**/dto/**,\
**/model/**,\
**/enums/**,\
**/repository/**,\
**/exception/**,\
**/*DTO*,\
**/*Dto*,\
**/*Record*,\
**/record/**,\
**/*Application*

#cobertura
#quarkus.jacoco.report=true
#quarkus.jacoco.minimum-coverage=0.70
#quarkus.jacoco.minimum-branch-coverage=0.60